export type Lang = "zh" | "en";

export const copy = {
  zh: {
    navBrandShort: "四柿",
    navBrandFull: "四个柿子",
    metaTitle: "四个柿子 · 面包与日常",
    metaDesc:
      "四个柿子烘焙 — 小而温暖的社区面包店品牌形象页（占位内容，仅作展示）。",
    langAria: "语言",
    langZh: "中",
    langEn: "EN",
    heroKicker: "邻里烘焙",
    heroTitle: "一块好面包。",
    heroTitleLine2: "平凡的一天也值得被接住。",
    heroSubline:
      "手工酸种 · 当季面团 · 慢一点的发酵。品牌展示页，占位图文可随意替换。",
    heroCtaPrimary: "了解我们",
    heroCtaSecondary: "营业时间",
    navAnchorSpotlight: "焦点",
    navAnchorStory: "主张",
    navAnchorVisit: "到店",
    spotlightLabel: "焦点",
    spotlightSub: "从面团到橱窗，用极简排版讲清一家小面包店在想什么。",
    spot1Title: "当季面团",
    spot1Body: "慢发酵带来的空气感与麦香。影像位预留。",
    spot1Cta: "探索",
    spot2Title: "晨光橱窗",
    spot2Body: "吐司与可颂在暖光里排队。影像位预留。",
    spot2Cta: "看看",
    spot3Title: "社区自取",
    spot3Body: "步行可达的外带动线。影像位预留。",
    spot3Cta: "路线",
    valuesLabel: "我们在意",
    aboutTitle: "关于我们",
    aboutBody:
      "四个柿子是一颗想象里的面包店名字：晨光、炉灶和一点甜。这里没有复杂的商业故事——只有对发酵、温度和时间的耐心。以下内容均为通用占位文案与示意布局，正式发布时可替换为您的品牌叙述。",
    craftTitle: "我们在意的事",
    craft1: "每日鲜烤，卖完即止",
    craft2: "配方干净，材料诚实",
    craft3: "尊重季节与本地物产",
    hoursTitle: "营业时间",
    hoursNote: "* 以上为示意时间，请以门店公告为准",
    weekdays: "周一至周五",
    weekend: "周末与节假日",
    closed: "店休 · 占位",
    galleryTitle: "氛围一角",
    galleryCaption: "品牌摄影待补充 — 占位色块示意橱窗与吐司纹理",
    assetsNote:
      "已获得授权的图片：在项目里复制 bakery-asset-urls.example.json 为 bakery-asset-urls.json，把各图的「可直接下载的图片 URL」（商家后台 CDN、OSS 直链等）填入对应文件名键，在项目根目录执行 npm run fetch:bakery-assets；再 npm run build 即可带上图。无法用机器人代登美团/大众点评抓取商户页。",
    contactTitle: "找到我们",
    addressLine: "幸福路 ×× 号（示意地址） · 中国城市",
    wechatPlaceholder: "微信：ShiziBread（占位）",
    phonePlaceholder: "电话：暂不公开 · 占位",
    backHomeAria: "返回 LavaAgent 主页",
    backHomeLabel: "返回主页",
    footerTiny: "四个柿子 · 品牌展示草稿 · ",
  },
  en: {
    navBrandShort: "4PX",
    navBrandFull: "Four Persimmons",
    metaTitle: "Four Persimmons · Bread & Routine",
    metaDesc:
      "Brand landing for a cosy neighborhood bakery (placeholder narrative for layout demo).",
    langAria: "Language",
    langZh: "中文",
    langEn: "EN",
    heroKicker: "Neighbourhood Bakery",
    heroTitle: "Good Bread.",
    heroTitleLine2: "Lift an ordinary day.",
    heroSubline:
      "Slow sourdough · seasonal dough · unhurried proofing. Demo layout — swap visuals anytime.",
    heroCtaPrimary: "Discover",
    heroCtaSecondary: "Hours",
    navAnchorSpotlight: "Spotlight",
    navAnchorStory: "Craft",
    navAnchorVisit: "Visit",
    spotlightLabel: "Spotlight",
    spotlightSub:
      "Minimal blocks and bold headlines—the kind of pacing you see on flagship retail sites, scaled for a small bakery demo.",
    spot1Title: "Seasonal dough",
    spot1Body: "Open crumb, warm crumb. Imagery pending.",
    spot1Cta: "Explore",
    spot2Title: "Morning window",
    spot2Body: "Croissants in soft light. Imagery pending.",
    spot2Cta: "View",
    spot3Title: "Neighbour pickup",
    spot3Body: "Walk-friendly to-go rhythm. Imagery pending.",
    spot3Cta: "Locate",
    valuesLabel: "What we uphold",
    aboutTitle: "About",
    aboutBody:
      "Four Persimmons is a fictional bakery name: morning light, the oven’s hum, and a little sweetness. The copy here is intentionally generic—a warm shell you can swap for your real brand story anytime.",
    craftTitle: "What we care about",
    craft1: "Bake fresh daily; sold until gone",
    craft2: "Straightforward formulas, honest sourcing",
    craft3: "Season-led, local-first mindset",
    hoursTitle: "Hours",
    hoursNote:
      "* Sample hours only — please follow in-store signage when launched",
    weekdays: "Mon · Fri",
    weekend: "Weekends · holidays",
    closed: "Closed · placeholder",
    galleryTitle: "A glimpse",
    galleryCaption:
      "Imagery pending — warm colour blocks as stand-ins for window light and crumb.",
    assetsNote:
      "Authorized photos: copy bakery-asset-urls.example.json to bakery-asset-urls.json, paste direct-download image URLs per key, run npm run fetch:bakery-assets then npm run build. We cannot log into Meituan/Dianping APIs to scrape storefront pages.",
    contactTitle: "Visit",
    addressLine: "Happiness Rd. ×× (sample) · Your city",
    wechatPlaceholder: "WeChat: ShiziBread (placeholder)",
    phonePlaceholder: "Phone: TBD · placeholder",
    backHomeAria: "Back to LavaAgent hub",
    backHomeLabel: "Home hub",
    footerTiny: "Four Persimmons · draft brand page · ",
  },
} as const;
