export type Lang = "zh" | "en";

export const copy = {
  zh: {
    navBrandShort: "四柿",
    navBrandFull: "四个柿子",
    metaTitle: "四个柿子 · 面包与日常",
    metaDesc:
      "四个柿子烘焙 — 小而温暖的社区面包店品牌形象页（占位内容，仅作展示）。",
    langAria: "语言",
    langZh: "中",
    langEn: "EN",
    heroKicker: "社区面包坊",
    heroTitle: "四个柿子",
    heroSubline: "用一块好面包接住平凡的一天 — 手作、当季、慢一点。",
    heroScroll: "了解我们",
    aboutTitle: "关于我们",
    aboutBody:
      "四个柿子是一颗想象里的面包店名字：晨光、炉灶和一点甜。这里没有复杂的商业故事——只有对发酵、温度和时间的耐心。以下内容均为通用占位文案与示意布局，正式发布时可替换为您的品牌叙述。",
    craftTitle: "我们在意的事",
    craft1: "每日鲜烤，卖完即止",
    craft2: "配方干净，材料诚实",
    craft3: "尊重季节与本地物产",
    hoursTitle: "营业时间",
    hoursNote: "* 以上为示意时间，请以门店公告为准",
    weekdays: "周一至周五",
    weekend: "周末与节假日",
    closed: "店休 · 占位",
    galleryTitle: "氛围一角",
    galleryCaption: "品牌摄影待补充 — 占位色块示意橱窗与吐司纹理",
    contactTitle: "找到我们",
    addressLine: "幸福路 ×× 号（示意地址） · 中国城市",
    wechatPlaceholder: "微信：ShiziBread（占位）",
    phonePlaceholder: "电话：暂不公开 · 占位",
    backHomeAria: "返回 LavaAgent 主页",
    backHomeLabel: "返回主页",
    footerTiny: "四个柿子 · 品牌展示草稿 · ",
  },
  en: {
    navBrandShort: "4PX",
    navBrandFull: "Four Persimmons",
    metaTitle: "Four Persimmons · Bread & Routine",
    metaDesc:
      "Brand landing for a cosy neighborhood bakery (placeholder narrative for layout demo).",
    langAria: "Language",
    langZh: "中文",
    langEn: "EN",
    heroKicker: "Neighbourhood Bakery",
    heroTitle: "Four Persimmons",
    heroSubline:
      "Good bread for ordinary days — slow proofing, humble ingredients.",
    heroScroll: "Discover",
    aboutTitle: "About",
    aboutBody:
      "Four Persimmons is a fictional bakery name: morning light, the oven’s hum, and a little sweetness. The copy here is intentionally generic—a warm shell you can swap for your real brand story anytime.",
    craftTitle: "What we care about",
    craft1: "Bake fresh daily; sold until gone",
    craft2: "Straightforward formulas, honest sourcing",
    craft3: "Season-led, local-first mindset",
    hoursTitle: "Hours",
    hoursNote:
      "* Sample hours only — please follow in-store signage when launched",
    weekdays: "Mon · Fri",
    weekend: "Weekends · holidays",
    closed: "Closed · placeholder",
    galleryTitle: "A glimpse",
    galleryCaption:
      "Imagery pending — colour blocks evoke window light and crumb texture.",
    contactTitle: "Visit",
    addressLine: "Happiness Rd. ×× (sample) · Your city",
    wechatPlaceholder: "WeChat: ShiziBread (placeholder)",
    phonePlaceholder: "Phone: TBD · placeholder",
    backHomeAria: "Back to LavaAgent hub",
    backHomeLabel: "Home hub",
    footerTiny: "Four Persimmons · draft brand page · ",
  },
} as const;
